### ISSUE TITLE
vision_msgs not present in the package

### ISSUE THREAD

**Issue by jocacace** [UtBotsAtHome-UTFPR/mediapipe_track#1]
Hi guys. Thanks for your work. I am trying to run the code, but the vision_msgs used (neither Skeleton2d nor Object) are present in the ros vision_msgs package. Are you using a different package for the messages? Is it possible to have a reference to that? 

Thanks!

**Comment by DavidSegalle** [comment]
Hello, I'm sorry for the delay. We are a student team and focusing on internal development.

vision_msgs is a series of custom messages we developed at https://github.com/UtBotsAtHome-UTFPR/utbots_vision/tree/master/vision_msgs
